name: DeepWTO
channels:
  - defaults
dependencies:
  - atomicwrites=1.3.0=py_0
  - attrs=18.2.0=py37h28b3542_0
  - blas=1.0=mkl
  - ca-certificates=2018.12.5=0
  - certifi=2018.11.29=py37_0
  - intel-openmp=2019.1=144
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - mkl=2019.1=144
  - mkl_fft=1.0.10=py37h5e564d8_0
  - mkl_random=1.0.2=py37h27c97d8_0
  - more-itertools=5.0.0=py37_0
  - ncurses=6.1=h0a44026_1
  - numpy=1.15.4=py37hacdab7b_0
  - numpy-base=1.15.4=py37h6575580_0
  - openssl=1.1.1a=h1de35cc_0
  - pandas=0.24.1=py37h0a44026_0
  - pip=18.1=py37_0
  - pluggy=0.8.1=py37_0
  - py=1.7.0=py37_0
  - pytest=4.2.1=py37_0
  - python=3.7.2=haf84260_0
  - python-dateutil=2.7.5=py37_0
  - pytz=2018.9=py37_0
  - readline=7.0=h1de35cc_5
  - setuptools=40.6.3=py37_0
  - six=1.12.0=py37_0
  - sqlite=3.26.0=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - wget=1.19.5=h051b688_0
  - wheel=0.32.3=py37_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - beautifulsoup4==4.7.1
    - bs4==0.0.1
    - pyyaml==3.13
    - selenium==3.141.0
    - soupsieve==1.7.3
    - tqdm==4.30.0
    - urllib3==1.24.1
prefix: /Users/zachary/anaconda3/envs/DeepWTO
