name: deepwto
channels:
  - https://conda.anaconda.org/t/QlQm-cgE-ok1/deepstudio
  - defaults
dependencies:
  - ca-certificates=2018.12.5=0
  - certifi=2018.11.29=py37_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - ncurses=6.1=h0a44026_1
  - openssl=1.1.1a=h1de35cc_0
  - pip=18.1=py37_0
  - python=3.7.2=haf84260_0
  - readline=7.0=h1de35cc_5
  - setuptools=40.6.3=py37_0
  - sqlite=3.26.0=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - wget=1.19.5=h051b688_0
  - wheel=0.32.3=py37_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - beautifulsoup4==4.7.1
    - bs4==0.0.1
    - selenium==3.141.0
    - soupsieve==1.7.3
    - tqdm==4.30.0
    - urllib3==1.24.1
prefix: /Users/zachary/anaconda3/envs/deepwto

